/*
 * Commands
 */

typedef enum
{
    CMD_QUIT,
    CMD_NEXT_FILE,
    CMD_PREVIOUS_FILE,
    CMD_MOVE_UP,
    CMD_MOVE_DOWN,
    CMD_MOVE_RIGHT,
    CMD_MOVE_LEFT,
    CMD_MOVE_FULL_PAGE_UP,
    CMD_MOVE_FULL_PAGE_DOWN,
    CMD_MOVE_FULL_PAGE_RIGHT,
    CMD_MOVE_FULL_PAGE_LEFT,
    CMD_MOVE_HALF_PAGE_UP,
    CMD_MOVE_HALF_PAGE_DOWN,
    CMD_MOVE_HALF_PAGE_RIGHT,
    CMD_MOVE_HALF_PAGE_LEFT,
    CMD_MOVE_LINE_END,
    CMD_MOVE_LINE_START,
    CMD_MOVE_FIRST_RECORD,
    CMD_MOVE_LAST_RECORD,
    CMD_MOVE_TOP_EDGE,
    CMD_MOVE_VERTICAL_MIDDLE,
    CMD_MOVE_BOTTOM_EDGE,
    CMD_MOVE_LEFT_EDGE,
    CMD_MOVE_HORIZONTAL_MIDDLE,
    CMD_MOVE_RIGHT_EDGE,
    CMD_INCREASE_HEADER_PANE_WIDTH,
    CMD_DECREASE_HEADER_PANE_WIDTH,
    CMD_INCREASE_RULER_PANE_HEIGHT,
    CMD_DECREASE_RULER_PANE_HEIGHT,
    CMD_INCREASE_TICK_SPACING,
    CMD_DECREASE_TICK_SPACING,
} Command;
