#ifndef FORMATS_H
#define FORMATS_H

/*
 * File format interface
 */

typedef enum
{
    FORMATS_ERROR_SUCCESS = 0,
    FORMATS_ERROR_INVALID_FORMAT = -1,
    FORMATS_ERROR_RECORD_OVERFLOW = -2,
    FORMATS_ERROR_SEQUENCE_OVERFLOW = -3,
    FORMATS_ERROR_FILE_IO = -4,
    FORMATS_ERROR_MEMORY_ALLOCATION = -5,
} FormatsError;

#endif // FORMATS_H