name: Build

on:
  release:
    types: [ published ]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Build project
      run: |
        make
    
    - uses: actions/upload-artifact@v4
      with:
        name: aalv-${{ matrix.os }}
        path: build/aalv
